module ReviewConfig exposing (config)

import NoMissingTypeAnnotation
import NoUnused.Dependencies
import NoUnused.Variables
import Review.Rule exposing (Rule)


config : List Rule
config =
    List.map ignoreGenerated
        [ NoUnused.Variables.rule
        , NoUnused.Dependencies.rule
        , NoMissingTypeAnnotation.rule
        ]


{-| `.elm-tailwind/` is generated by elm-tailwind-classes from the Tailwind
theme. It is a source directory so Elm can compile against it, but it is not
ours to lint.
-}
ignoreGenerated : Rule -> Rule
ignoreGenerated =
    Review.Rule.ignoreErrorsForDirectories [ ".elm-tailwind" ]
